# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title:            Prajventures
description: > # this means to ignore newlines until "email:"
    I mostly rant about life

email: spspkand@uwaterloo.ca
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Prajna Kandarpa'
author: 'Prajna Kandarpa'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://prajnak.github.io/blog" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@aqjq'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/aqjq
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: lastfm	
    url:	www.last.fm/user/prahladk
    desc: Spy on my music
    share_url: 
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/prajnak
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
