# Dependencies
markdown:        kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            The Talon Blog
tagline:          'Our journey to improve drone deliveries'
url:              http://hyde.getpoole.com
baseurl:          /blog

author:
  name:           'Talon Team'
  url:            https://github.com/talonco

paginate:         5
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/talonco/blog
