# Dependencies
markdown:        kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            The Talon Blog
tagline:          'Our journey to improve drone deliveries'
url:              http://hyde.getpoole.com
baseurl:          "/blog"

author:
  name:           'Talon Team'
  url:            https://github.com/talonco

paginate:         5
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/talonco/blog

prose:
  rooturl: '_posts'
  siteurl: 'http://talonco.github.io/blog'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "author"
        field: 
          element: "select"
          label: "Add Author"
          placeholder: "Prajna Kandarpa"
          value: praj
          options:
            - name: "Prajna Kandarpa"
              value: praj
            - name: "Wesley Groom"
              value: wesley
            - name: "Sebastian Mocny"
              value: sebastian
            - name: "Craig Vandenburg"
              value: craig
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Interesting"
              value: interesting
            - name: "DevOps"
              value: devops
            - name: "Development"
              value: development
            - name: "Startups"
              value: startups
          alterable: true
